### ISSUE TITLE
Sketchbook location is incorrect?

### ISSUE THREAD

**Issue by alexdmiller** [processing/processing-library-template#59]
### Describe the bug

The `build.gradle.kts` file assumes your sketchbook lives at `"$userHome/Documents/Processing/sketchbook"`. However, the default location (AFAIK) is `"$userHome/Documents/Processing"`. 

### Steps to reproduce

1. Follow the [getting started](https://processing.github.io/processing-library-template/getting-started.html) guide
2. Run the `deployToProcessingSketchbook` gradle step

### Expected behavior

Library should appear in the Processing libraries folder

### Actual behavior

Library isn't written to libraries folder

**Comment by mingness** [comment]
Hello @alexdmiller , 
Thanks for your bug report. Is it correct to say, that you are running Processing on a Mac?

Could you copy here the location on your computer of the libraries folder? it would be something like 
$userHome/Documents/Processing/sketchbook/libraries, 
or as suggested by your bug report,
$userHome/Documents/Processing/libraries

Judging from the Processing4/3 code base, there should be a child folder named "sketchbook" regardless of platform.

I recommend to run the Gradle task "buildReleaseArtifacts" before running "deployToProcessingSketchbook". While it shouldn't matter, since "buildReleaseArtifacts" is a dependency for "deployToProcessingSketchbook", I've noticed the task won't complete the very first time.

**Comment by mingness** [comment]
Having done more research into the matter, I see that Macs and the sketchbook folder have a tenuous relationship - Macs by default don't have a literal sketchbook folder, but sometimes one can get  a no sketchbook error for various reasons. I'll change the Gradle build file to test for the literal sketchbook folder, with default to the filepath without the literal sketchbook folder. Thanks for bringing this to my attention.

**Comment by mingness** [comment]
PR #61 fixed this issue.
